# Site settings
title: Kazoo Blog
SEOTitle: 王小买的博客 | Kazoo Blog
header-img: https://kazoottt-1256684243.cos.ap-chengdu.myqcloud.com/home-bg.jpg
email: wangyijin1999@qq.com
url: "https://http://kazoottt.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
# RSS: true
github_username: KazooTTT
juejin_username: 3087084380501815

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: kazoo310

# Analytics settings
# Baidu Analytics
# ba_track_id: '41fb7b65befdc0e7640ed12c642a88c4'

# Google Analytics
ga_track_id: "UA-144235674-1" # Format: UA-xxxxxx-xx
ga_domain: kazoottt.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "保持学习的习惯"
sidebar-avatar: https://avatars2.githubusercontent.com/u/31075337?s=460&u=a9742b0a63b5e2c1e229465201657906f4a317af&v=4 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true

# Friends
friends:
  [
    { title: "ClowNaxcvd", href: "http://www.yuuuuang.com" },
    { title: "HuaiYing", href: "https://blog.csdn.net/huaiyingdetective" },
  ]
